Completed the tasks
KSUGraduationProject/Python-tasks pull request #2
Opened 2020-12-10 08:00 UTC by AlaaElden98

2020-12-10 08:21 UTC, HassanElDesouky requested changes
Everything looks good! Thank you for working on this. I left a couple of things inline. Please take a look at them and we will be ready to go. 🚀

2020-12-10 08:21 UTC, HassanElDesouky commented on Tasks/Alaa.py
> -"""
Why did you delete this?

2020-12-10 08:21 UTC, HassanElDesouky commented on Tasks/Alaa.py
> +        return "error"
Returning "error" doesn't really mean anything, and isn't helpful at all... What about something like... "Error: Can't sum these values." or something even more descriptive.

2020-12-10 08:21 UTC, HassanElDesouky commented on Tasks/Alaa.py
> +        return int(first_number / second_number)
This will work fine. However, there's an operator in Python which yields the same result, it's the `//` operator. So if you'd like to change it, it would be something like:
```python
return first_number // second_number
```

2020-12-10 08:21 UTC, HassanElDesouky commented on Tasks/Alaa.py
> -4. Write a function that prints the even numbers from a given list.
I think you forgot to write a function that "prints the even numbers from a given list".

2020-12-10 08:21 UTC, HassanElDesouky commented on Tasks/Alaa.py
> +class TestTasks(unittest.TestCase):
I think you forgot to test `is_valid_data_type`. It's very important to test it since you're relying on it in most of your other functions.

2020-12-10 19:20 UTC, AlaaElden98 commented on Tasks/Alaa.py
> -"""
Why should I keep them?

2020-12-10 19:58 UTC, AlaaElden98 commented on Tasks/Alaa.py
> -"""
I delete them because I read in the "clean code" book that it's not a good practice to have unnecessary comments

2020-12-10 20:08 UTC, HassanElDesouky requested changes
This is very very good! Thank you for working on this. Just one little more thing... while you were working on this and committing your code, you will find out that there are more than 5 commits in this PR and counting.

It's much better if we can combine all of these commits to a single commit (since all of them serve the same logic which in our case is "Completing the task").

I encourage you to take a look at `git squash`, squash your commits, push again, and I'll be happy to merge your changes! :)

For reference, you can take a look at this video: https://www.youtube.com/watch?v=viY1BbKZhSI

2020-12-11 05:12 UTC, HassanElDesouky approved these changes
Thank you!

2020-12-11 05:14 UTC, HassanElDesouky commented
@AlaaElden98 can you just resolve the conflict so I will be able to merge?

2020-12-11 07:07 UTC, HassanElDesouky approved these changes
I resolved the confilict. Merging ⛵

2020-12-11 07:08 UTC, merged