add new functions and make unit test
KSUGraduationProject/Python-tasks pull request #3
Opened 2020-12-10 20:46 UTC by YahiaAshraf74

2020-12-10 20:57 UTC, HassanElDesouky requested changes
Looks great! Thanks. 

I left a couple of comments in-line, however the most important thing IMO is the `xml` files. We shouldn't keep track or commit these files at all because they will be different for each one committing to the repo.

2020-12-10 20:57 UTC, HassanElDesouky commented on .idea/Python-tasks.iml
> +<module type="PYTHON_MODULE" version="4">
We should't keep track of `xml` files in git. Please, remove these files.

2020-12-10 20:57 UTC, HassanElDesouky commented on Tasks/Yahia.py
> +    # TODO How we test void function
A way to do it is to return an array of even numbers. Then you will be able to test it easily.

2020-12-10 20:57 UTC, HassanElDesouky commented on Tasks/Yahia.py
> +    # TODO handle pass whole datatype in python
What's the problem with testing this function?

2020-12-11 15:25 UTC, YahiaAshraf74 commented on Tasks/Yahia.py
> +    # TODO handle pass whole datatype in python
No, a problem at all, I just add TODO to make it later because I don't know the whole datatypes in python.

2020-12-11 15:26 UTC, YahiaAshraf74 commented on Tasks/Yahia.py
> +    # TODO handle pass whole datatype in python
@HassanElDesouky 
Also, I just wonder should I write the unit test for this function, because it just uses a builtin funcion?

2020-12-11 15:28 UTC, HassanElDesouky commented on Tasks/Yahia.py
> +    # TODO handle pass whole datatype in python
Hmm, fair enough. I think since it's using a library function there's no point for us to test it.

2020-12-11 15:28 UTC, YahiaAshraf74 commented on Tasks/Yahia.py
> +    # TODO How we test void function
Okay, the task statement is a little bit confused for return type (void or array)

2020-12-11 15:29 UTC, YahiaAshraf74 commented on Tasks/Yahia.py
> +    # TODO How we test void function
Anyway if you know how to test the void function just tell me because I search but didn't find anything clear so far

2020-12-11 15:29 UTC, HassanElDesouky commented on Tasks/Yahia.py
> +    # TODO How we test void function
Yeah, I realized that, my bad sorry.

2020-12-11 16:12 UTC, HassanElDesouky requested changes
Okay great! I think the only thing remaining is to remove the `.xml` and `.gitignore` files. So, you're only changing one file.

2020-12-11 16:15 UTC, YahiaAshraf74 commented
> Okay great! I think the only thing remaining is to remove the `.xml` and `.gitignore` files. So, you're only changing one file.

2020-12-11 16:19 UTC, HassanElDesouky approved these changes
Great work. Thank you. ⛵

2020-12-11 16:20 UTC, merged